# Triangle, pentagonal, and hexagonal numbers are generated by
# the following formulae:

# Triangle        T_n = n(n + 1)/2     1, 3, 6, 10, 15, ...
# Pentagonal      P_n = n(3n - 1)/2    1, 5, 12, 22, 35, ...
# Hexagonal       H_n = n(2n - 1)      1, 6, 15, 28, 45, ...

# It can be verified that T_285 = P_165 = H_143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

from math import sqrt

def is_pentagonal(num):
	tmp = (sqrt(24 * num + 1) + 1) / 6
	return int(tmp) == tmp

def is_hexagonal(num):
	tmp = (sqrt(8 * num + 1) + 1) / 4
	return int(tmp) == tmp

n = 286

while True:
	tmp = n * (n + 1) / 2
	if is_pentagonal(tmp) and is_hexagonal(tmp):
		print tmp
		break
	n += 1
